import time
import colorama
from colorama import Fore

a = print (Fore.GREEN + "Enter your threads")
time.sleep (23.2141)
print (Fore.BLUE + "[!]     Captcha dected ")
time.sleep (5)

print (Fore.BLUE + "[!]     Captcha dected ")
time.sleep (5)
print (Fore.BLUE + "[!]     Captcha dected ")
time.sleep (5)
print (Fore.green + "{+}    Hcaptcha solved")
time.sleep (5)
print (Fore.green + "{+}    Hcaptcha solved")
time.sleep (5)
print (Fore.green + "{+}    Hcaptcha solved")
time.sleep (7)
print (Fore.BLUE + "($)     humaized token. Added pfp")
time.sleep (2)
print (Fore.blue + "($)     humaized added bio")
time.sleep (8)
print (Fore.blue + "($)     humaized added pronouns")
time.sleep (2)
print (Fore.BLUE + "($)     humaized token. Added pfp")
time.sleep (6)
print (Fore.blue + "($)     humaized added bio")
time.sleep (2)
print (Fore.blue + "($)     humaized added pronouns")
time.sleep (3)
print (Fore.blue + "($)     humaized added bio")
time.sleep (5)
print (Fore.blue + "($)     humaized added pronouns")
time.sleep (5)
print (Fore.blue + "($)     humaized added pfp")
time.sleep (2)
print (Fore.LIGHTBLUE_EX + "(+)     Email verified")
time.sleep (9)
print (Fore.LIGHTBLUE_EX + "(+)     Email verified")
time.sleep (3)
print (Fore.LIGHTBLUE_EX + "(+)     Email verified")
time.sleep (9)
print (Fore.red + "Result token MTExODY1NDiVCi7JfEfdpWh8M0QWBsHpjTKa.XAl1HF.AV5rURqR6nNG9i3e3QWHSlNEi860_vorawcl2-XsFbGNGUwVjrDp9U")
time.sleep (10)
print (Fore.red + "Result token MTExODY1NDReS9shMhtP4qVRQsIiZTDehWgv.1YHuxI.aEzualrHvU7oV02PSwhuyjMfbxit_IDDRY00Y-3MCALkoTqUK3g7wX")
time.sleep (7)
print (Fore.red + "Result token MTExODY1NDXJft6lIzCBfCs2HSZmGLrTVLGh.QSymvh.ldBd16L6BhGguKTnBBOTNwJ2suGq_0A97OhQu-DKntPW7nTylQIrIg")
